config/routes.rb
Rails.application.routes.draw do
  resources :students do
  resources :addresses

  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  has_many :addresses
  has_many :courses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    student = Student.find(params[:student_id])
    student.addresses.create(address_params)
    redirect_to student_path(student)
  end


  private

  def address_params
    params.require(:address).permit(:description, :city, :stret, :zip, :state)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = Student.find(params[:id])
    @addresses = @student.addresses
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.new(student_params)
    if student.save
      flash[:success] = "#{student.name} is created!"
      redirect_to student_path(student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student = Student.find(params[:id])
    student.update(student_params)
    if student.save
      flash[:success] = "#{student.name} updated!"
      redirect_to student_path(student)
    else
      render :edit
    end
  end

  def destroy
    student = Student.destroy(params[:id])
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:name)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<%=form_for [@student, @address] do |f| %>
  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.label :city %>
  <%= f.text_area :city %>

  <%= f.label :state%>
  <%= f.text_area :state %>

  <%= f.label :zip%>
  <%= f.text_area :zip %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<%= link_to 'Students', students_path %>
<%= link_to 'Create New Student', new_student_path %>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>
  <%=f.submit%>
  <%end%>

app/views/students/edit.html.erb
<h3> Edit a student </h3>

<%= render partial: "form" %>

app/views/students/index.html.erb
<ul>
  <li>
  <%@students.each do |s| %>
  <%=link_to "#{s.name}", student_path(s) %>
  <%= link_to "Delete", student_path(s), method: :delete %>
  <%end%>
</li>
</ul>

app/views/students/new.html.erb
<h3> Create new student! </h3>

<%= form_for @student do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>
  <%=f.submit%>
  <%end%>

app/views/students/show.html.erb
<h3> <%=@student.name%> <h3>
  <%@addresses.each do |a| %>
    <h4> <%=a.description%> </h4>
    <h4> <%=a.city%> </h4>
    <h4> <%=a.street%> </h4>
    <h4> <%=a.state%> </h4>
    <h4> <%=a.zip%> </h4>
  <%end%>